#ifndef _FLASH_LAYOUT_H
#define _FLASH_LAYOUT_H

/*This is automatically generated by cmake, don't edit manually! Change Cmake configuration for other values (CMakeLists.txt & .h.in file)*/
/* AVR_MCU = atmega16 */

#define NRF_CODE_ADDR              0x2840             //NRF24 code starting address in flash
#define NRF_CODE_SIZE              4096             //NRF24 code SIZE [Bytes]

#define BOOTLOADER_CODE_ADDR       0x3800      //BOOTLOADER code starting address in flash
#define BOOTLOADER_CODE_SIZE       2048      //BOOTLOADER code SIZE [Bytes]

#define NRF_HOOKS_ADDR             0x2800            //NRF24 HOOKS code starting address in flash
#define NRF_HOOKS_SIZE             64            //NRF24 HOOKS SIZE [Bytes]

#define FLASH_PAGE_COUNT           80          //The total number of flash pages
#define FLASH_PAGE_SIZE            128           //The size of one page in [Bytes]

#define APP_CODE_ADDR              0x0             //APP code starting address in flash
#define APP_CODE_SIZE              10240             //APP code SIZE [Bytes]

#define SPI_MEMORY              __attribute__((section(".nrf24")))
#define NRF24_MEMORY            __attribute__((section(".nrf24")))
#define RADIO_FPTRS_MEMORY      __attribute__((used, section(".radio_fptrs")))

#endif
